apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: green-deployment
  template:
    metadata:
      labels:
        name: green-deployment
    spec:
      containers:
        - image: adamtravis/rollouts:green
          name: green-deployment
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: green-deployment
  labels:
    name: green-deployment
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  selector:
    name: green-deployment
  type: NodePort
